### ISSUE TITLE
Clarify a little bit how to use

### ISSUE THREAD

**Issue by decimoseptimo** [angeloashmore/gatsby-plugin-local-search#20]
given your [how to use](https://github.com/angeloashmore/gatsby-plugin-local-search#how-to-use), consider this scenario:
-Search by _title_ but not by _body_
-When a _title_ is found, pull the _body_ data

The way I've been using it, is searching all data, and that had a severe performance downgrade in the lighthouse test.

**Comment by decimoseptimo** [comment]
Is what I'm asking the [`index` plugin options?](https://github.com/angeloashmore/gatsby-plugin-local-search/commit/a68a1635a03b2e9b96acc98341f2fd59e15e6f17)

**Comment by angeloashmore** [comment]
Hi @decimoseptimo, yes, `index` is what you're looking for.

Your `normalizer` function should return data that should either be indexed, stored, or both.

Typically you would want to index as few fields as possible to keep the index size small. Your store can contain the larger fields that are needed to display the results, but may not be necessary to index.

**Comment by decimoseptimo** [comment]
Glad to hear that, I'm currently researching performance bottelnecks, and this was one of them, now it seems fixed. 
One last thing, does `ref: 'id'` have to match graphql `id`? i ended up using `ref: '_id'` since i use `_id`. Is not a problem, just wondering.

**Comment by angeloashmore** [comment]
Good question! No, it does not need to match. If you set `ref` to `_id`, just make sure your `normalizer` function returns an `_id` property.

It defaults to `id` just as a convention but you can set anything as your ref.
