### ISSUE TITLE
The page for the package on Gatsby site is broken

### ISSUE THREAD

**Issue by crutchcorn** [angeloashmore/gatsby-plugin-local-search#3]
https://www.gatsbyjs.org/packages/gatsby-plugin-local-search/?=search

**Comment by angeloashmore** [comment]
@crutchcorn I believe this happens when a non-latest version (e.g. `next`) is pushed to NPM.

@khwkang just pushed `v1.0.0` to latest so we should see the page update shortly.

Thanks for the heads up!
