### ISSUE TITLE
All fields in lunr index

### ISSUE THREAD

**Issue by javialon26** [angeloashmore/gatsby-plugin-local-search#35]
When Lunr engine is used the index option is omitted and all fields from the normalizer are used. 

[This line](https://github.com/angeloashmore/gatsby-plugin-local-search/blob/master/src/gatsby-node.ts#L51) always resolves to all fields in the document.

**Comment by angeloashmore** [comment]
Thank you for finding this! I'll merge in the PR (#36) and publish a new version.

**Comment by angeloashmore** [comment]
Published in `v2.0.1`
